//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "friends")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub min_user_guid: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub max_user_guid: Uuid,
    pub min_user_guid_decision: bool,
    pub max_user_guid_decision: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_data::Entity",
        from = "Column::MaxUserGuid",
        to = "super::user_data::Column::Guid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserData2,
    #[sea_orm(
        belongs_to = "super::user_data::Entity",
        from = "Column::MinUserGuid",
        to = "super::user_data::Column::Guid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserData1,
}

impl ActiveModelBehavior for ActiveModel {}
