//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod hooks;

pub mod prelude;

pub mod user_data;
pub mod perm_container;
pub mod perm_container_container_rel;
pub mod perm_container_perm_rel;
pub mod perm_container_wildcard_rel;
pub mod perm_wildcard;
pub mod permission;