//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "perm_container_perm_rel")]
pub struct Model {
    pub value: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub perm_container_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub perm_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::perm_container::Entity",
        from = "Column::PermContainerId",
        to = "super::perm_container::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PermContainer,
    #[sea_orm(
        belongs_to = "super::permission::Entity",
        from = "Column::PermId",
        to = "super::permission::Column::PermId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Permission,
}

impl Related<super::perm_container::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermContainer.def()
    }
}

impl Related<super::permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Permission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
