//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "perm_container")]
pub struct Model {
    pub visible_in_search: bool,
    pub visible_in_profile: bool,
    pub name: Option<String>,
    pub pin_link: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub weight: i32,
    pub color: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::perm_container_perm_rel::Entity")]
    PermContainerPermRel,
    #[sea_orm(has_many = "super::perm_container_wildcard_rel::Entity")]
    PermContainerWildcardRel,
    #[sea_orm(has_many = "super::user_data::Entity")]
    UserData,
}

impl Related<super::perm_container_perm_rel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermContainerPermRel.def()
    }
}

impl Related<super::perm_container_wildcard_rel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermContainerWildcardRel.def()
    }
}

impl Related<super::user_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserData.def()
    }
}

impl Related<super::perm_wildcard::Entity> for Entity {
    fn to() -> RelationDef {
        super::perm_container_wildcard_rel::Relation::PermWildcard.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::perm_container_wildcard_rel::Relation::PermContainer
                .def()
                .rev(),
        )
    }
}

impl Related<super::permission::Entity> for Entity {
    fn to() -> RelationDef {
        super::perm_container_perm_rel::Relation::Permission.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::perm_container_perm_rel::Relation::PermContainer
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
