//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::permission_group::Entity")]
    PermissionGroup,
    #[sea_orm(has_many = "super::permission_user::Entity")]
    PermissionUser,
}

impl Related<super::permission_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermissionGroup.def()
    }
}

impl Related<super::permission_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermissionUser.def()
    }
}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        super::permission_group::Relation::Group.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::permission_group::Relation::Permission.def().rev())
    }
}

impl Related<super::user_data::Entity> for Entity {
    fn to() -> RelationDef {
        super::permission_user::Relation::UserData.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::permission_user::Relation::Permission.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
