//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "perm_container_wildcard_rel")]
pub struct Model {
    pub value: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub perm_container_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub perm_wildcard_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::perm_container::Entity",
        from = "Column::PermContainerId",
        to = "super::perm_container::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PermContainer,
    #[sea_orm(
        belongs_to = "super::perm_wildcard::Entity",
        from = "Column::PermWildcardId",
        to = "super::perm_wildcard::Column::PermWildcardId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PermWildcard,
}

impl Related<super::perm_container::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermContainer.def()
    }
}

impl Related<super::perm_wildcard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PermWildcard.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
