//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "perm_container_container_rel")]
pub struct Model {
    pub value: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub perm_container_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub child_perm_container_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::perm_container::Entity",
        from = "Column::ChildPermContainerId",
        to = "super::perm_container::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PermContainer2,
    #[sea_orm(
        belongs_to = "super::perm_container::Entity",
        from = "Column::PermContainerId",
        to = "super::perm_container::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PermContainer1,
}

impl ActiveModelBehavior for ActiveModel {}
