//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::perm_container::Entity as PermContainer;
pub use super::perm_container_container_rel::Entity as PermContainerContainerRel;
pub use super::perm_container_perm_rel::Entity as PermContainerPermRel;
pub use super::perm_container_wildcard_rel::Entity as PermContainerWildcardRel;
pub use super::perm_wildcard::Entity as PermWildcard;
pub use super::permission::Entity as Permission;
pub use super::user_data::Entity as UserData;
