//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::group::Entity as Group;
pub use super::permission::Entity as Permission;
pub use super::permission_group::Entity as PermissionGroup;
pub use super::permission_user::Entity as PermissionUser;
pub use super::user_data::Entity as UserData;
pub use super::user_group::Entity as UserGroup;
