//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::friends::Entity as Friends;
pub use super::post::Entity as Post;
pub use super::user_data::Entity as UserData;
pub use super::user_mini_profile::Entity as UserMiniProfile;
pub use super::user_profile::Entity as UserProfile;
