[package]
name = "lwapi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"

axum = {version = "0.8.1", features = ["macros", "json", "ws"]}
tokio = {version = "1.43.0", features = ["full"] }
axum-extra = { version = "0.10.0", features = ["cookie"] }
cookie = "0.18.1"
async-graphql-axum = "7.0.14"

uuid = { version = "1.12.1", features = ["serde", "v4"] }
rand = "0.9.0"
tracing = { version = "0.1.41", features = ["async-await"] }
bcrypt = "0.16.0"   
chrono = "0.4.39"
regex = "1.11.1"
jsonwebtoken = {version="9.3.0", features = ["use_pem"]}

oauth2 = "4.4.2"
google-gmail1 = "6.0.0"

reqwest = { version = "0.12.12", features = ["json"] }
lazy_static = "1.5.0"
dotenvy = "0.15.7"
tracing-subscriber = "0.3.19"

diesel =  { version = "2.2.6", features = ["postgres", "uuid", "serde_json"] }
dsync = "0.1.0"
deadpool-diesel = { version = "0.6.1", features = ["postgres", "tracing"] }
deadpool-sync = "0.1.4"
redis = { version = "0.28.2", features = ["r2d2", "tokio-comp", "ahash", "json"] }
r2d2 = "0.8.10"
tower = { version = "0.5.2", features = ["full"] }
tower-http = "0.6.2"
anyhow = "1.0.95"
include-bytes-plus = "1.1.0"


[target.x86_64-pc-windows-msvc.pq]
rustc-link-search = ["C:\\Program Files\\PostgreSQL\\17\\lib"]
rustc-link-lib = ["libpq"]

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "reg"
path = "src/main.rs"

[[bin]]
name = "auth"
path = "src/auth_service.rs"

[[bin]]
name = "auth_legacy"
path = "src/auth_service_legacy.rs"

[[bin]]
name = "calls"
path = "src/calls_service.rs"

[[bin]]
name = "dsync"
path = "src/dsync.rs"
