[workspace]
members = [
    # "libs/appstate",
    "libs/shared",
    "libs/shared_cookies",
    "libs/shared_db",
    "libs/shared_tokens",
    "services/auth",
    # "services/old-auth",
    ]
resolver = "2"

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"