services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: always
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - memory
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./db_data:/data