services:
  # test_postgre:
  #   env_file: 
  #     - ".cfg"
  #     - ".env"
  #   image: postgres:17.4-alpine3.21
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD}
  #     POSTGRES_USER: ${TEST_DATABASE_USER}
  #     POSTGRES_DB: ${TEST_DATABASE_DB}
  #   ports:
  #     - "${TEST_DATABASE_PORT}:5432"
  # test_redis:
  #   env_file:
  #     - ".cfg"
  #     - ".env"
  #   image: redis:7.2.4-alpine
  #   restart: always
  #   ports:
  #     - "${TEST_REDIS_PORT}:6379"
  #   command: redis-server --save 20 1 --loglevel warning
  test_yugabyte:
    env_file:
      - ".cfg"
      - ".env"
    image: yugabytedb/yugabyte:latest
    restart: always
    ports:
      - "${TEST_DATABASE_PORT}:5433"  # YCQL/YCQL port
      - "15434:15433"                  # Web UI (optional)
    command: "/home/yugabyte/bin/yugabyted start --daemon=false --tserver_flags=enable_ysql=true --master_flags=ysql_enable_auth=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15434"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_dragonfly:
    env_file:
      - ".cfg"
      - ".env"
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: always
    ports:
      - "${TEST_REDIS_PORT}:6379"
    volumes:
      - ./dbs/dragonfly:/data
    command: --snapshot_cron="*/5 * * * *"
volumes:
  test-redis: