services:
  test_postgre:
    env_file: 
      - ".cfg"
      - ".env"
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    volumes:
      - ./dbs/init_postgre.sql:/docker-entrypoint-initdb.d/init.sql
      - test-postgre:/var/lib/postgresql/data
  test_redis:
    env_file:
      - ".cfg"
      - ".env"
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "${TEST_REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - test-redis:/data
volumes:
  test-postgre:
  test-redis: