services:
  cockroachdb:
    env_file: .env
    image: cockroachdb/cockroach:v20.2.5
    command: start-single-node --insecure
    restart: always
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data