services:
  postgre:
    env_file: "shared.env"
    image: postgres:17.4-alpine3.21
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./dbs/postgre-data:/var/lib/postgresql/data
  redis:
    env_file: "shared.env"
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./dbs/redis:/data
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
volumes:
  redis:
    driver: local