services:
  postgre:
    env_file: 
      - ".cfg"
      - ".env"
    image: postgres:17.4-alpine3.21
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./dbs/postgre-data:/var/lib/postgresql/data
  redis:
    env_file:
      - ".cfg"
      - ".env"
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./dbs/redis:/data
  nats:
    env_file:
      - ".cfg"
      - ".env"
    image: nats:latest
    container_name: nats_server
    ports:
      - "${NATS_PORT}:4222"
      - "${NATS_MONITOR_PORT}:8222"
    command: ["-js"] # todo: add storage?
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"  # Это порт, на котором будет доступен интерфейс RedisInsight
    volumes:
      - redisinsight-data:/root/.redisinsight  # Сохранение настроек RedisInsight
    restart: always
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
volumes:
  redisinsight-data: